update code build

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -8,6 +8,23 @@ BUILD_DIR=${1:-}
 CACHE_DIR=${2:-}
 ENV_DIR=${3:-}
 
+# Fail immediately on non-zero exit code.
+set -e
+# Fail immediately on non-zero exit code within a pipeline.
+set -o pipefail
+# Fail on undeclared variables.
+set -u
+# Debug, echo every command
+#set -x
+
+function indent() {
+c='s/^/       /'
+case $(uname) in
+	Darwin) sed -l "$c";;
+	*)      sed -u "$c";;
+esac
+}
+
 if [ -f $ENV_DIR/PROJECT_PATH ]; then
 	PROJECT_PATH=`cat $ENV_DIR/PROJECT_PATH`
 
@@ -19,7 +36,6 @@ if [ -f $ENV_DIR/PROJECT_PATH ]; then
 		echo "       created tmp dir: $TMP_DIR"
         echo "       moving working dir: $PROJECT_PATH to $TMP_DIR"
 		cp -R $BUILD_DIR/$PROJECT_PATH/. $TMP_DIR/
-
 	 	echo "       cleaning build dir $BUILD_DIR"
 		rm -rf $BUILD_DIR/*
 		echo "       copying preserved work dir from cache $TMP_DIR to build dir $BUILD_DIR"
@@ -29,26 +45,9 @@ if [ -f $ENV_DIR/PROJECT_PATH ]; then
 		exit 0
 	fi
 
-	# Fail immediately on non-zero exit code.
-	set -e
-	# Fail immediately on non-zero exit code within a pipeline.
-	set -o pipefail
-	# Fail on undeclared variables.
-	set -u
-	# Debug, echo every command
-	#set -x
-
-	function indent() {
-	c='s/^/       /'
-	case $(uname) in
-		Darwin) sed -l "$c";;
-		*)      sed -u "$c";;
-	esac
-	}
-
-	BUILD_DIR=$1
-	CACHE_DIR=$2
-	ENV_DIR=$3
+	BUILD_DIR_CLIENT=$1
+	CACHE_DIR_CLIENT=$2
+	ENV_DIR_CLIENT=$3
 	BP_DIR=`cd $(dirname $0); cd ..; pwd`
 
 	# Switch to new Node auto build behavior ahead of release
@@ -56,7 +55,7 @@ if [ -f $ENV_DIR/PROJECT_PATH ]; then
 
 	# Use architecture of multi-buildpack to compose behavior.
 	# https://github.com/heroku/heroku-buildpack-multi
-	cp $BP_DIR/.buildpacks $BUILD_DIR/.buildpacks
+	cp $BP_DIR/.buildpacks $BUILD_DIR_CLIENT/.buildpacks
 	url=https://github.com/heroku/heroku-buildpack-multi.git
 	branch=""
 	dir=$(mktemp -t buildpackXXXXX)
@@ -82,7 +81,7 @@ if [ -f $ENV_DIR/PROJECT_PATH ]; then
 
 	if [ $? == 0 ]; then
 	echo "=====> Detected Framework: $framework"
-	$dir/bin/compile $BUILD_DIR $CACHE_DIR $ENV_DIR
+	$dir/bin/compile $BUILD_DIR_CLIENT $CACHE_DIR_CLIENT $ENV_DIR_CLIENT
 
 	if [ $? != 0 ]; then
 		exit 1
